apiVersion: apps/v1
kind: Deployment
metadata:
  name: a1quest-admin-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      name: a1quest-admin-web
      labels:
        app: admin
    spec:
      containers:
        - image: kanagatech/a1questweb:latest
          name: a1quest-admin-web
          ports:
          - containerPort: 3000  
           
---
# Node Port Service For Admin-web
apiVersion: v1
kind: Service
metadata:
  name: a1quest-admin-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 31600
      targetPort: 3000
  selector:
    app: admin
